apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}-deployment"
  labels:
    app: acc-calc-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app:  "{{  .Chart.Name }}-selector"
  template:
    metadata:
      labels:
        app: "{{  .Chart.Name }}-selector"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.applicationPort}}
          
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 5
