apiVersion: v1
kind: Service
metadata:
  name: "{{  .Chart.Name }}-service"
  labels:
    app: "{{  .Chart.Name }}-selector"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: calc-Port
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.applicationPort }}
  selector:
    app: "{{  .Chart.Name }}-selector"
