# Default values for helmacc-calc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  registry: docker.io
  repository: shashikverma/apprepo
  tag: acc-dv
  pullPolicy: IfNotPresent
  
  readinessProbe: {}

  livenessProbe: {}


applicationPort: 80

service:
  name: node
  type: ClusterIP
  port: 80